### PR TITLE
fix(column value parsing): fix parsing all values for each related column type

### LINKED ISSUE #663: Errors on updating a table row
To have a tracking issue, this happend to a user when trying to update a row:

│[warning] 2023-11-10T09:25:25.000 tables Value 6 could not be parsed for column Subscription │
│[warning] 2023-11-10T09:25:25.000 tables An internal error or exception occurred: Column with id 965 is not part of view with id 12

Reloading made it work but the first warning is still logged

### LINKED ISSUE #667: Link type columns seems only to work for external URL's
### Steps to reproduce

1. create a Link type column
2. use "edit row"
3. add a file from Nextcloud / a Kontakt /  via built in search feature
4. click save

### Expected behavior

a clickable link to the resources should be stored and rendered.

### Actual behavior

get two On Screen Error messages but no linked file in your row:
-> row could not be updatet
-> row could not be updatet unknown Error
(loos translation from German)

### Tables app version

0.6.1

### Browser

Firefox 119

### Client operating system

_No response_

### Operating system

_No response_

### Web server

None

### PHP engine version

None

### Database

None

### Additional info

[index] Fehler: Exception: OCA\Tables\Service\RowService::parseValueByColumnType(): Argument #1 ($value) must be of type string, null given, called in /var/www/html/custom_apps/tables/lib/Service/RowService.php on line 198 in file '/var/www/html/custom_apps/tables/lib/Service/RowService.php' line 212 at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\Tables\\C ... "], "updateSet")
1. /var/www/html/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main("OCA\\Tables\\Controller\\RowController", "updateSet", ["OC\\AppFramewo ... "], ["60","tables.row.updateSet"])
2. /var/www/html/lib/base.php line 1065
   OC\Route\Router->match("/apps/tables/row/60")
3. /var/www/html/index.php line 36
   OC::handleRequest()

Caused by:

TypeError: OCA\Tables\Service\RowService::parseValueByColumnType(): Argument #1 ($value) must be of type string, null given, called in /var/www/html/custom_apps/tables/lib/Service/RowService.php on line 198 at <<closure>>

 0. /var/www/html/custom_apps/tables/lib/Service/RowService.php line 198
    OCA\Tables\Service\RowService->parseValueByColumnType("*** sensitive parameters replaced ***", ["OCA\\Tables\\Db\\Column",40])
 1. /var/www/html/custom_apps/tables/lib/Service/RowService.php line 316
    OCA\Tables\Service\RowService->cleanupData("*** sensitive parameters replaced ***", [["OCA\\Tables\\ ... "], 3, "*** sensitive parameters replaced ***")
 2. /var/www/html/custom_apps/tables/lib/Controller/RowController.php line 112
    OCA\Tables\Service\RowService->updateSet("*** sensitive parameters replaced ***")
 3. /var/www/html/custom_apps/tables/lib/Controller/Errors.php line 16
    OCA\Tables\Controller\RowController->OCA\Tables\Controller\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/html/custom_apps/tables/lib/Controller/RowController.php line 107
    OCA\Tables\Controller\RowController->handleError(["Closure"])
 5. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Tables\Controller\RowController->updateSet("*** sensitive parameters replaced ***")
 6. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController(["OCA\\Tables\\C ... "], "updateSet")
 7. /var/www/html/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\Tables\\C ... "], "updateSet")
 8. /var/www/html/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main("OCA\\Tables\\Controller\\RowController", "updateSet", ["OC\\AppFramewo ... "], ["60","tables.row.updateSet"])
 9. /var/www/html/lib/base.php line 1065
    OC\Route\Router->match("/apps/tables/row/60")
10. /var/www/html/index.php line 36
    OC::handleRequest()

PUT /apps/tables/row/60
from 46.142.36.120 by veit at 2023-11-10T12:43:47+01:00

### LINKED ISSUE #672: Column of type Selection not saving first item selected in row.
### Steps to reproduce

1. Create a table column of type selection
2. Add 2 items
3. Add row and select first item and save row
4. The item doesn't display in the table. It's blank. This only happens when selecting the first item. Selecting item 2 works as it should.

### Expected behavior

When saving the row I expect to see the selected item in the row. 

### Actual behavior

The column is blank.

### Tables app version

0.6.1

### Browser

FF 64bit 119.0 1

### Client operating system

Win 10

### Operating system

RaspberryPi OS 64bit

### Web server

Nginx

### PHP engine version

PHP 8.2

### Database

MariaDB

### Additional info

_No response_

### LINKED ISSUE #674: Number column: typing a decimal point deletes field content
### Steps to reproduce

1. Set the system decimal separator to a `comma`, and the numeric keypad on your keyboard is set to `period`
2. Add column of type `Number` with at least `1` decimal
3. Add a new row, type some numbers in the field, then type the decimal point on your numeric keypad : this will delete the numbers you previously typed

### Expected behavior

The `period` character should not cause the previous numbers to be deleted.
Better way would be to convert it to the expected decimal separator.

### Actual behavior

Typing the `period` character will delete the numbers you previously typed.
On a computer keyboard I have the option to type the comma on the alphabetic keyboard, this is annoying but it works.
But on a phone keyboard this field calls the numeric keyboard only, on which I have only the option to type a decimal period, causing the deletion of previous numbers.

### Tables app version

0.6.1

### Browser

Firefox 119

### Client operating system

Linux / Android

### Operating system

Ubuntu 22.04.3

### Web server

Apache

### PHP engine version

PHP 8.1

### Database

MariaDB

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by datenangebot**
- allow empty values and parse them correctly
- handle selection ids and labels to match to the defined options
- cleanup

closes #663 
closes #672 
closes #674 
closes #667

### CODE REVIEW

File: lib/Service/ColumnTypes/DatetimeBusiness.php [hunk 1]
```diff
@@ -9,9 +9,11 @@
 class DatetimeBusiness extends SuperBusiness implements IColumnTypeBusiness {
 
 	/**
-	 * @throws Exception
+	 * @param mixed $value (string|null)
+	 * @param Column|null $column
+	 * @return string
 	 */
-	public function parseValue(string $value, ?Column $column = null): string {
+	public function parseValue($value, ?Column $column = null): string {
```
Comment (juliushaertl) [inline lib/Service/ColumnTypes/DatetimeBusiness.php:16]:
```suggestion
	public function parseValue(?string $value, ?Column $column = null): string {
```

Why not this?

Comment (juliushaertl) [reply lib/Service/ColumnTypes/DatetimeBusiness.php:16]: Another note, the method itself does no null check, so it would still be passed to DateTime would cause a deprecation warning from PHP, so better catch that earlier and return.

Comment (datenangebot) [reply lib/Service/ColumnTypes/DatetimeBusiness.php:16]: Because that would not match the definition from the interface

File: lib/Service/ColumnTypes/SelectionBusiness.php [hunk 2]
```diff
@@ -6,31 +6,66 @@
...
 		if(!$column) {
 			$this->logger->warning('No column given, but expected on parseValue for SelectionBusiness');
 			return '';
 		}
 
-		foreach ($column->getSelectionOptionsArray() as $option) {
-			if($option['label'] === $value) {
-				return json_encode($option['id']);
+		$intValue = (int) $value;
+		if ("".$intValue === $value) {
```
Comment (juliushaertl) [inline lib/Service/ColumnTypes/SelectionBusiness.php:21]:
```suggestion
		if ((string)$intValue === $value) {
```

File: lib/Service/ColumnTypes/DatetimeBusiness.php (hunk 1 above)
Comment (datenangebot) [reply lib/Service/ColumnTypes/DatetimeBusiness.php:16]: Honestly the datetime type is the last I have to update and add tests. So yes, needs to be covered.

File: lib/Service/ColumnTypes/SelectionBusiness.php (hunk 2 above)
Comment (datenangebot) [reply lib/Service/ColumnTypes/SelectionBusiness.php]: yes better

File: lib/Service/ColumnTypes/SelectionMultiBusiness.php [hunk 3]
```diff
@@ -8,48 +8,95 @@ class SelectionMultiBusiness extends SuperBusiness implements IColumnTypeBusines
...
 
-	public function canBeParsed(string $value, ?Column $column = null): bool {
+	/**
+	 * @param mixed $value (int[]|string|null) Array of option IDs or string with comma seperated labels
+	 * @param Column|null $column
+	 * @return bool
+	 */
+	public function canBeParsed($value, ?Column $column = null): bool {
 		if(!$column) {
+			$this->logger->warning('No column given, but expected on canBeParsed for SelectionBusiness');
```
Comment (juliushaertl) [inline lib/Service/ColumnTypes/SelectionMultiBusiness.php:77]: This log message is probably not very useful without either an exception trace or logging additional details about the column and what value was passed, or?

File: lib/Service/ColumnTypes/SelectionMultiBusiness.php [hunk 4]
```diff
@@ -8,48 +8,95 @@ class SelectionMultiBusiness extends SuperBusiness implements IColumnTypeBusines
...
+		$wasString = false;
+		if (is_string($value)) {
+			$value = array_map('trim', explode(',', $value));
+			$wasString = true;
+		}
+
+		foreach ($value as $wantedValue) {
+			if(!$wasString) {
+				$wantedValue = (int) $wantedValue;
+			}			if ($this->getOptionIdForValue((int) $wantedValue) === null) {
```
Comment (juliushaertl) [inline lib/Service/ColumnTypes/SelectionMultiBusiness.php:96]:
```suggestion
			}
			if ($this->getOptionIdForValue((int) $wantedValue) === null) {
```

**Review by juliushaertl — CHANGES_REQUESTED** [review]
Small comments inline, otherwise 👍

File: lib/Service/ColumnTypes/SelectionMultiBusiness.php (hunk 3 above)
Comment (datenangebot) [reply lib/Service/ColumnTypes/SelectionMultiBusiness.php:77]: Something like this?
`$this->logger->warning('No column given, but expected on parseValue for SelectionBusiness', ['exception' => new \Exception()]);
`

File: lib/Service/ColumnTypes/DatetimeBusiness.php (hunk 1 above)
Comment (juliushaertl) [reply lib/Service/ColumnTypes/DatetimeBusiness.php:16]: Ok, then let's keep the mixed type but properly check that it is a string and otherwise return early.

Comment (datenangebot) [reply lib/Service/ColumnTypes/DatetimeBusiness.php:16]: suggest to track that here: https://github.com/nextcloud/tables/issues/676 and accept for this PR as this is like it was before. 🤷🏻‍♂️

File: lib/Service/ColumnTypes/SelectionMultiBusiness.php (hunk 3 above)
Comment (juliushaertl) [reply lib/Service/ColumnTypes/SelectionMultiBusiness.php:77]: Yes, looks sane

**Review by juliushaertl — APPROVED** [review]
