### PR TITLE
fix: Properly display teams in usergroup

### LINKED ISSUE #1751: Adding Teams to a row is broken
### Steps to reproduce

1. Create a table with a row which allows to select users, groups and teamsImage

2. Go back to the table and create a row where you select a team in the corresponding row

### Expected behavior

Result correctly shown in the table

### Actual behavior

While creating a row I can select a team (in this example "Sales Engieerung (2)" is a team):

Image

After clicking on save the table looks good (beside that the avatar for the team is not show correctly):

Image

After reload the team name changes into a cryptical, probably internal ID:

Image

### Tables app version

0.9.0

### Browser

_No response_

### Client operating system

_No response_

### Operating system

_No response_

### Web server

None

### PHP engine version

None

### Database

None

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by enjeck**
fixes #1751

Now, it shows the team display name, not the ID. Plus, an icon is used to indicate it's a team:
image

### CODE REVIEW

File: lib/Db/RowCellUsergroupMapper.php [hunk 1]
```diff
@@ -34,7 +39,12 @@ public function applyDataToEntity(Column $column, RowCellSuper $cell, $data): vo
 	}
 
 	public function formatEntity(Column $column, RowCellSuper $cell) {
-		$displayName = $cell->getValueType() === 0 ? ($this->userManager->getDisplayName($cell->getValue()) ?? $cell->getValue()) : $cell->getValue();
+		$displayName = $cell->getValue();
+		if ($cell->getValueType() === UsergroupType::USER) {
+			$displayName = $this->userManager->getDisplayName($cell->getValue()) ?? $cell->getValue();
```
Comment (blizzz) [inline lib/Db/RowCellUsergroupMapper.php:44]: fwiw groups also have displaynames

Comment (enjeck) [reply lib/Db/RowCellUsergroupMapper.php:46]: Thanks!
