### PR TITLE
fix(design): remove share icon if listed in share-list

### LINKED ISSUE #530: Hide share icon on shared tables in nav

### PR DESCRIPTION
**Pull request by datenangebot**
closes #530 

SCR-20230912-jndi

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

File: src/modules/navigation/partials/NavigationTableItem.vue [hunk 1]
```diff
@@ -128,6 +128,10 @@ export default {
 			type: String,
 			default: '',
 		},
+		isSharedItem: {
+		      type: Boolean,
+		      default: false,
+		    },
```
Comment (juliushaertl) [inline src/modules/navigation/partials/NavigationTableItem.vue:134]: Indentation seems off

Comment (datenangebot) [reply src/modules/navigation/partials/NavigationTableItem.vue:134]: seems to be a general problem. Will merge here...

Comment (datenangebot) [reply src/modules/navigation/partials/NavigationTableItem.vue:134]: in IDE seems to be good?! 💁🏻‍♂️
SCR-20230912-jovv

**Comment by juliushaertl** [comment]
Might be an upstream issue https://github.com/nextcloud-libraries/eslint-config/blob/master/parts/vue.js#L9 is not setting https://eslint.vuejs.org/rules/script-indent.html

**Review by juliushaertl — APPROVED** [review]

**Review by juliushaertl — APPROVED** [review]
