### PR TITLE
fix: ensure default values show as filled

### LINKED ISSUE #993: Leaving default value qualifies as not filled
### Steps to reproduce

1. Create a new column of type numeric, for example "quantity".
2. Set default value to 1.
3. Set required to true
4. Add new row. Leave our field value as default (1).

### Expected behavior

Default value should be acceptable

### Actual behavior

You get an error, saying that you should fill all required fields

### Tables app version

0.6.6

### Browser

Firefox 124.0.2

### Client operating system

Any

### Operating system

Ubuntu 22.04

### Web server

Apache

### PHP engine version

PHP 8.1

### Database

PostgreSQL

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by enjeck**
fixes #993

### CODE REVIEW

**Comment by elzody** [comment]
Seems reasonable, just a weird Cypress error. I am assuming it is related since it's affecting the `column-number.cy.js` test, but have not looked into it.

**Comment by juliushaertl** [comment]
I am wondering if instead of filling the default value then we should rather use the placeholder attribute and andjudt the check to allow empty fields for values that have a default? That way a default value would also adapt if changed on the table level.

**Comment by enjeck** [comment]
> I am wondering if instead of filling the default value then we should rather use the placeholder attribute and andjudt the check to allow empty fields for values that have a default? That way a default value would also adapt if changed on the table level.

I just noticed that this problem also affects other column types, not just numbers. Would look into making this approach more generic

File: src/shared/components/ncTable/mixins/rowHelper.js [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+			const columnTypeDefault = type + 'Default'
+			if (column.type === ColumnTypes.Selection) {
+				if (
+					(value instanceof Array && value.length > 0)
+					|| (value === parseInt(value))
+				) {
+					return true
+				}
+				const hasDefaultValue = columnTypeDefault in column && !(['', 'null'].includes(column[columnTypeDefault]))
+				return false || hasDefaultValue
```
Comment (elzody) [inline src/shared/components/ncTable/mixins/rowHelper.js:15]: What's stopping from just returning `hasDefaultValue`? having the `false ||` seems redundant to me, since if `hasDefaultValue` is false, it'll just return false anyway. Unless I don't understand the logic correctly?

**Review by elzody — APPROVED** [review]

**Comment by juliushaertl** [comment]
Don't be too hesitant to click the merge button if it is green 😁
