### PR TITLE
Fix/547 views filter metacolumns

### LINKED ISSUE #547: Filter in Views - Metadaten
### Steps to reproduce

Mit Erstellung einer neuen Zeile wird sowohl das Standard-Feld "Erstellt am" als auch "Zuletzt bearbeitet am" mit demselben Wert gespeichert. Dies machen wir uns zu nutze, damit neue Einträge für eine bestimmte Gruppe über eine View gefiltert angezeigt werden.

1. Tabelle "A": Spalte "Titel" (Text)
2. View "New Items": Filter Spalte "Erstellt am", Bedingung "Ist gleich", Wert "Zuletzt bearbeitet am" kann nicht aus den vorhandenen Spalten selektiert werden.
3. Auch die Eingabe nur eines Datum (z. B. Wert 2023-09-13) ist nicht möglich

### Expected behavior

Vergleich vorhandener Metadaten-Spalten ("Erstellt am" = "Zuletzt bearbeitet am") => neuer Eintrag

### Actual behavior

Es kann nur ein Wert eingegeben werden. Allerdings funktioniert es nicht mit Schema "YYYY-MM-DD".

### Tables app version

0.6.0-beta.3

### Browser

Chrome 115.0.5790.111

### Client operating system

_No response_

### Operating system

_No response_

### Web server

None

### PHP engine version

None

### Database

None

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by datenangebot**
closes #547

### CODE REVIEW

File: src/modules/main/partials/editViewPartials/filter/FilterEntry.vue [hunk 1]
```diff
@@ -129,10 +129,19 @@ export default {
 		},
 		magicFields() {
 			if (this.selectedColumn && this.selectedColumn.type.substr(0, 9) !== 'selection') {
+				const mf = []
```
Comment (juliushaertl) [inline src/modules/main/partials/editViewPartials/filter/FilterEntry.vue:132]: Nitpick: Would prefer a more clear variable name

```suggestion
				const fields = []
```

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
@datenangebot Left a nitpick and disabled automerge to leave it to you to adjust or merge

File: src/modules/main/partials/editViewPartials/filter/FilterEntry.vue [hunk 2]
```diff
@@ -129,10 +129,19 @@ export default {
 		},
 		magicFields() {
 			if (this.selectedColumn && this.selectedColumn.type.substr(0, 9) !== 'selection') {
+				const fields = []
+				this.selectedColumn.getPossibleMagicFields().forEach(field => {
+					if (field.id.substr(0, 1) !== '@') {
+						const id = field.id
+						field.id = '@' + id
+					}
+					mf.push({ ...field })
```
Comment (juliushaertl) [inline src/modules/main/partials/editViewPartials/filter/FilterEntry.vue:138]: Other usages also need the renaming adjustment

File: src/modules/main/partials/editViewPartials/filter/FilterEntry.vue [hunk 3]
```diff
@@ -129,10 +129,19 @@ export default {
...
+				})
 				if (this.term) {
-					return [this.term, ...this.selectedColumn.getPossibleMagicFields()]
+					return [this.term, mf]
```
Comment (juliushaertl) [inline src/modules/main/partials/editViewPartials/filter/FilterEntry.vue:141]: Same here

File: src/modules/main/partials/editViewPartials/filter/FilterEntry.vue [hunk 4]
```diff
@@ -129,10 +129,19 @@ export default {
...
+				} else {
+					return mf
```
Comment (juliushaertl) [inline src/modules/main/partials/editViewPartials/filter/FilterEntry.vue:143]: And here

**Review by juliushaertl — CHANGES_REQUESTED** [review]

**Review by juliushaertl — APPROVED** [review]
