### PR TITLE
Fix/692

### LINKED ISSUE #692: parse values for number columns throws errors
1. create a number column
2. set min to 0.5
3. open "create row"
4. console will show up

`Cannot read properties of null (reading 'replace')`

### PR DESCRIPTION
**Pull request by datenangebot**
closes #692 

also fixes:
- handle empty values for number columns correctly
- allow to remove column number config values
- add validation for default value in combination with min and max

SCR-20231122-iwzg

### CODE REVIEW

File: lib/Service/ColumnService.php [hunk 1]
```diff
@@ -362,48 +362,30 @@ public function update(
 			if ($subtype !== null) {
 				$item->setSubtype($subtype);
 			}
-			if ($numberPrefix !== null) {
+			if($numberPrefix !== null) {
```
Comment (juliushaertl) [inline lib/Service/ColumnService.php:365]:
```suggestion
			if ($numberPrefix !== null) {
```

Not sure why php-cs-fixer doesn't complain or auto fix this, but would be more aligned to the rest of the code base

File: lib/Service/ColumnService.php [hunk 2]
```diff
@@ -362,48 +362,30 @@ public function update(
...
 				$item->setNumberPrefix($numberPrefix);
 			}
-			if ($numberSuffix !== null) {
+			if($numberSuffix !== null) {
```
Comment (juliushaertl) [inline lib/Service/ColumnService.php:368]:
```suggestion
			if ($numberSuffix !== null) {
```

**Review by juliushaertl — APPROVED** [review]
