### PR TITLE
fix(design): adjust close options

### LINKED ISSUE #348: Close Button for fullscreen editor on the wrong place
### Steps to reproduce

-

### Expected behavior

-

### Actual behavior

SCR-20230609-kcya

### Tables app version

_No response_

### Browser

_No response_

### Client operating system

_No response_

### Operating system

_No response_

### Web server

None

### PHP engine version

None

### Database

None

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by datenangebot**
- put close button to the right
- add closing X for modal

closes #348 

new:
SCR-20230609-kgst

### CODE REVIEW

File: src/shared/components/ncTable/partials/rowTypePartials/TextRichForm.vue [hunk 1]
```diff
@@ -11,13 +11,13 @@
...
 			</NcButton>
-			<NcModal v-if="showBigEditorModal" :close-button-contained="true" size="full" :title="column.title" @close="showBigEditorModal = false">
+			<NcModal v-if="showBigEditorModal" :close-button-contained="false" size="full" @close="showBigEditorModal = false">
 				<div class="row">
 					<div class="fix-col-4">
 						<NcEditor :text.sync="localValue" :show-border="false" />
 					</div>
 				</div>
-				<div class="closeModalButton">
+				<div class="closeModalButton row space-R">
```
Comment (juliushaertl) [inline src/shared/components/ncTable/partials/rowTypePartials/TextRichForm.vue:20]: Haven't tested yet but how does the button align when there is long text so that the editor scrolls?

Comment (datenangebot) [reply src/shared/components/ncTable/partials/rowTypePartials/TextRichForm.vue]: I changed to to a fixed button. Might be better to have it always visible...

**Review by juliushaertl — APPROVED** [review]
