### PR TITLE
fix: make the userId configurable for the analytics data provider to use

### LINKED ISSUE #464: AnalyticsDatasource error on 0.6.0-beta.1
```
{
  "reqId": "vXWpGRi4KlEUiw5xVSBA",
  "level": 3,
  "time": "2023-08-11T14:45:35+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "analytics",
  "method": "",
  "url": "--",
  "message": "Can not initialize data source: \"OCA\\\\Tables\\\\Datasource\\\\AnalyticsDatasource\"",
  "userAgent": "--",
  "version": "27.1.0.0",
  "data": {
    "app": "analytics"
  }
}
```

As we had some large refactoring and feature merged with views, this likely needs some adjustment. Having a proper exception trace would be quite nice in addition as well as test coverage for the data source. ;)

FYI @Rello

### PR DESCRIPTION
**Pull request by datenangebot**
closes #464

### CODE REVIEW

File: lib/Api/V1Api.php [hunk 1]
```diff
@@ -9,12 +9,13 @@
 
 class V1Api {
 	private RowService $rowService;
-
 	private ColumnService $columnService;
+	private string $userId;
 
-	public function __construct(ColumnService $columnService, RowService $rowService) {
+	public function __construct(ColumnService $columnService, RowService $rowService, string $userId) {
```
Comment (juliushaertl) [inline lib/Api/V1Api.php:15]:
```suggestion
	public function __construct(ColumnService $columnService, RowService $rowService, ?string $userId) {
```

Dependency injection might pass in null, so this should be allowed to avoid errors in the logs

Comment (juliushaertl) [reply lib/Api/V1Api.php:15]: You might want to instead check and throw an error in places where it is used

**Review by juliushaertl — CHANGES_REQUESTED** [review]
Small comment regarding the constructor, otherwise seems good

File: lib/Api/V1Api.php (hunk 1 above)
Comment (datenangebot) [reply lib/Api/V1Api.php]: > You might want to instead check and throw an error in places where it is used

That should be handled by the permissions service.

**Review by juliushaertl — APPROVED** [review]
