### PR TITLE
fix(Favorites): repair runtime cache population

### LINKED ISSUE #1350: Favorite/Unfavorite does not work properly
See videos below
[Screencast_20240912_115839.webm](https://github.com/user-attachments/assets/a9f2488a-4802-4c76-a584-eafe37c9c1e7)
[Screencast_20240912_115123.webm](https://github.com/user-attachments/assets/83a7fdab-810c-476f-9bde-02e56efa3a75)

### PR DESCRIPTION
**Pull request by blizzz**
fixes #1350 

The data was stored correctly, but the retrieval was borked.

### CODE REVIEW

File: lib/Service/FavoritesService.php [hunk 1]
```diff
@@ -48,7 +48,7 @@ public function isFavorite(int $nodeType, int $id): bool {
 
 			$result = $qb->executeQuery();
 			while ($row = $result->fetch()) {
-				$this->cache->set($cacheKey, true);
+				$this->cache->set(sprintf('%d_%d', $row['node_type'], $row['node_id']), true);
```
Comment (juliusknorr) [inline lib/Service/FavoritesService.php:51]: Good catch, just cacheKey is unsed now ;)

Comment (blizzz) [reply lib/Service/FavoritesService.php:51]: Negative, returned in line 55 related to the method parameters.

Comment (juliusknorr) [reply lib/Service/FavoritesService.php:51]: Right, sorry seems I mixed up closing brackets and missed that part

**Review by juliusknorr — APPROVED** [review]
